import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CreateRembolso from '../view/CreateRembolso'

export default function Home () {
  return (
    <>
      <Head>
        <title>Tesoreria Grupo Intecsa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CreateRembolso />
      </main>
    </>
  )
}
