import Head from 'next/head'
import HomeDashboard from '../view/HomeDashboard'

export default function Home () {
  return (
    <>
      <Head>
        <title>Tesoreria Grupo Intecsa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ width: '70vw' }}>
        <h1>
          Tesoreria Grupo Intecsa
        </h1>
        <section>
          <HomeDashboard />
        </section>
      </main>
    </>
  )
}
